### ISSUE TITLE
What does undefined local('') do in CSS snippets?

### ISSUE THREAD

**Issue by ClarusDignus** [majodev/google-webfonts-helper#144] opened 2022-03-29 12:10 UTC
Does the undefined `local('')` mean: _use_ local font or _ignore_ local font?

E.g.:

```
/* roboto-regular - latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: url('roboto-v29-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('roboto-v29-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('roboto-v29-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('roboto-v29-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('roboto-v29-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('roboto-v29-latin-regular.svg#Roboto') format('svg'); /* Legacy iOS */
}
```

**Comment by gsauthof** [comment] 2022-05-14 20:59
Duplicate of: #124

**Comment by bdlowery** [comment] 2022-06-19 07:32
> Duplicate of: #124

There's literally no solution to the problem in that thread.

**Comment by gsauthof** [comment] 2022-07-06 20:59
> There's literally no solution to the problem in that thread.

This is sad, but doesn't make it less of a duplicate.
Also the other issue is still open.
Having multiple issues open for the same problem doesn't necessarily help to arrive at a resolution faster.
Fragmentation makes it harder to track.

**Comment by majodev** [comment] 2023-01-29 17:47
[v1.1.0](https://github.com/majodev/google-webfonts-helper/releases/tag/v1.1.0) removes `local('')`

**Closed by majodev** 2023-01-29 17:47 UTC
