### ISSUE TITLE
Looks like the some of the font files are false (e.g. Open Sans)

### ISSUE THREAD

**Issue by agoat** [majodev/google-webfonts-helper#23] opened 2016-05-12 12:41 UTC
When I look into the Open Sans font, some font weights (e.g. 300 or 600) are some kind of a serif fonts but not the Open Sans.

**Comment by majodev** [comment] 2016-05-12 18:55
duplicate of #21 - woff2 files were not downloaded correctly - closing.

**Closed by majodev** 2016-05-12 18:55 UTC
